#!/bin/sh
# Generates compose/appsettings.json on first run from the shipped
# example, substituting per-deployment values: the public hostname
# from compose/.env and a freshly-generated XorKey.
#
# Idempotent: if appsettings.json already exists, exits 0 without
# touching it. Operators who want to re-render must delete the file
# first.
#
# Called automatically by `make platform-up` as a prerequisite. Can
# also be run on its own (`make init-config`).

set -eu

cd "$(dirname "$0")/../compose"

if [ -f appsettings.json ]; then
    echo "compose/appsettings.json already exists — leaving it alone."
    echo "  (delete it first if you want to regenerate from the example)"
    exit 0
fi

if [ ! -f appsettings.example.json ]; then
    echo "ERROR: compose/appsettings.example.json missing — can't bootstrap." >&2
    exit 1
fi

# Load .env so PUBLIC_ENTRY / WORKSPACE are available. The file uses
# shell-style KEY=VALUE so `. ./.env` works.
if [ ! -f .env ]; then
    if [ -f .env.example ]; then
        cp .env.example .env
        chmod 600 .env
        echo "compose/.env missing — copied compose/.env.example as a starter." >&2
        echo "  Edit it to set PUBLIC_ENTRY + ACME_EMAIL, then re-run." >&2
        echo "  (Or run 'make wizard' from the repo root for an interactive setup.)" >&2
        exit 1
    fi
    echo "ERROR: compose/.env missing and no .env.example to copy from." >&2
    exit 1
fi
# shellcheck disable=SC1091
. ./.env

# Hard-fail if PUBLIC_ENTRY is still the placeholder.
PUBLIC_ENTRY="${PUBLIC_ENTRY:-}"
case "$PUBLIC_ENTRY" in
    ""|*"{{"*"}}"*|"<"*">"*)
        echo "ERROR: PUBLIC_ENTRY in compose/.env is unset or still the placeholder." >&2
        echo "  Set it to your platform's public hostname (e.g. ctf.example.com)." >&2
        exit 1
        ;;
esac

# WORKSPACE is just a docker-compose project name + traefik route
# suffix — auto-pick something slug-safe if the operator left the
# placeholder. Rotating it later means losing the existing
# docker-compose project's volume bindings, so we persist the chosen
# value back to .env (same caveat as XorKey).
WORKSPACE="${WORKSPACE:-}"
case "$WORKSPACE" in
    ""|*"{{"*"}}"*|"<"*">"*)
        if command -v openssl >/dev/null 2>&1; then
            WS_SUFFIX="$(openssl rand -hex 4)"
        elif [ -r /dev/urandom ]; then
            WS_SUFFIX="$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n')"
        else
            WS_SUFFIX="default"
        fi
        WORKSPACE="gzctf-$WS_SUFFIX"
        # Overwrite the placeholder line if present, otherwise append.
        if grep -qE '^WORKSPACE=' .env; then
            # Portable in-place: write to temp + replace
            sed 's|^WORKSPACE=.*|WORKSPACE="'"$WORKSPACE"'"|' .env > .env.tmp \
                && mv .env.tmp .env
        else
            printf '\nWORKSPACE="%s"\n' "$WORKSPACE" >> .env
        fi
        echo "Auto-picked WORKSPACE=$WORKSPACE (persisted to .env)"
        ;;
esac

# Generate a strong XorKey (used to obfuscate registry passwords + repo
# binding tokens at rest). 64 hex chars = 256 bits of entropy.
if [ -n "${XOR_KEY:-}" ]; then
    XK="$XOR_KEY"
else
    if command -v openssl >/dev/null 2>&1; then
        XK="$(openssl rand -hex 32)"
    elif [ -r /dev/urandom ]; then
        XK="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    else
        echo "ERROR: openssl missing and /dev/urandom unreadable — can't generate XorKey." >&2
        exit 1
    fi
    # Persist so re-runs land on the same key (important: rotating XorKey
    # breaks every encrypted token + registry password already in the DB).
    if [ -w .env ]; then
        printf '\n# Auto-generated by scripts/init-config.sh on %s\nXOR_KEY=%s\n' \
            "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$XK" >> .env
    fi
fi

# A&D SSH jump-host internal secret. gzctf reads it from appsettings.json
# (Ad:Ssh:InternalSecret, substituted below); the ssh-jump sidecar reads it from .env
# (INTERNAL_SECRET=$AD_SSH_INTERNAL_SECRET). We write the SAME value to BOTH, exactly
# like XorKey, so they can't diverge. The platform REFUSES the shipped placeholder, so a
# real value is required or `ssh <challenge-id>@host -p 22022` stays disabled. 256 bits.
if [ -n "${AD_SSH_INTERNAL_SECRET:-}" ]; then
    SSH_SECRET="$AD_SSH_INTERNAL_SECRET"
else
    if command -v openssl >/dev/null 2>&1; then
        SSH_SECRET="$(openssl rand -hex 32)"
    elif [ -r /dev/urandom ]; then
        SSH_SECRET="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    else
        echo "ERROR: openssl missing and /dev/urandom unreadable — can't generate AD_SSH_INTERNAL_SECRET." >&2
        exit 1
    fi
    if [ -w .env ]; then
        printf '\n# Auto-generated by scripts/init-config.sh on %s\nAD_SSH_INTERNAL_SECRET=%s\n' \
            "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$SSH_SECRET" >> .env
    fi
fi

# Generate the seed Admin password if missing. PrelaunchHelper reads
# this env var on first boot to create the 'Admin' user (Role=Admin).
# Subsequent boots ignore it. Operators who ran scripts/wizard.sh
# already have it; this branch handles the edit-.env-by-hand path.
ADMIN_PASSWORD_GENERATED=
if [ -z "${ADMIN_PASSWORD:-}" ]; then
    # Prefix 'Aa1' to satisfy ASP.NET Identity's default password
    # policy (uppercase + lowercase + digit required). Without it,
    # the PrelaunchHelper's CreateAsync would silently fail and no
    # Admin user would exist.
    if command -v openssl >/dev/null 2>&1; then
        ADMIN_PASSWORD="Aa1$(openssl rand -hex 12)"
    elif [ -r /dev/urandom ]; then
        ADMIN_PASSWORD="Aa1$(head -c 12 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    else
        echo "ERROR: openssl missing and /dev/urandom unreadable — can't generate ADMIN_PASSWORD." >&2
        exit 1
    fi
    ADMIN_PASSWORD_GENERATED=1
    if [ -w .env ]; then
        printf '\n# Auto-generated by scripts/init-config.sh on %s\nADMIN_PASSWORD=%s\n' \
            "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$ADMIN_PASSWORD" >> .env
    fi
fi
export ADMIN_PASSWORD

# Generate the postgres password if missing. Compose passes the same
# value to the db container's POSTGRES_PASSWORD env var, so they stay
# in sync. The 'Aa1' prefix matches the ADMIN_PASSWORD scheme (not
# required for postgres, but harmless and consistent). DO NOT rotate
# once set — postgres only consumes POSTGRES_PASSWORD on its very
# first init; later changes need ALTER USER inside a running db.
if [ -z "${POSTGRES_PASSWORD:-}" ]; then
    if command -v openssl >/dev/null 2>&1; then
        POSTGRES_PASSWORD="Aa1$(openssl rand -hex 16)"
    elif [ -r /dev/urandom ]; then
        POSTGRES_PASSWORD="Aa1$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
    else
        echo "ERROR: openssl missing and /dev/urandom unreadable — can't generate POSTGRES_PASSWORD." >&2
        exit 1
    fi
    if [ -w .env ]; then
        printf '\n# Auto-generated by scripts/init-config.sh on %s\nPOSTGRES_PASSWORD=%s\n' \
            "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$POSTGRES_PASSWORD" >> .env
    fi
fi
export POSTGRES_PASSWORD

# Render with literal-string sed substitutions. The example uses
# `{{.PublicEntry}}`, `{{.XorKey}}`, `{{.PostgresPassword}}` (gzcli
# placeholder style). Escape any sed-special chars in the values.
escape_sed() {
    printf '%s' "$1" | sed 's|[\\&|]|\\&|g'
}
PUBLIC_ENTRY_ESC=$(escape_sed "$PUBLIC_ENTRY")
CHALLENGE_BASE_DOMAIN="${CHALLENGE_BASE_DOMAIN:-chall.$PUBLIC_ENTRY}"
CHALLENGE_BASE_DOMAIN_ESC=$(escape_sed "$CHALLENGE_BASE_DOMAIN")
XK_ESC=$(escape_sed "$XK")
PG_ESC=$(escape_sed "$POSTGRES_PASSWORD")
SSH_SECRET_ESC=$(escape_sed "$SSH_SECRET")
SSH_PORT="${AD_SSH_PUBLIC_PORT:-22022}"

sed \
    -e "s|{{\\.PublicEntry}}|$PUBLIC_ENTRY_ESC|g" \
    -e "s|{{\\.ChallengeBaseDomain}}|$CHALLENGE_BASE_DOMAIN_ESC|g" \
    -e "s|{{\\.XorKey}}|$XK_ESC|g" \
    -e "s|{{\\.PostgresPassword}}|$PG_ESC|g" \
    -e "s|{{\\.AdSshInternalSecret}}|$SSH_SECRET_ESC|g" \
    -e "s|{{\\.AdSshPublicPort}}|$SSH_PORT|g" \
    appsettings.example.json > appsettings.json

chmod 600 appsettings.json

echo "Generated compose/appsettings.json"
echo "  PUBLIC_ENTRY = $PUBLIC_ENTRY"
echo "  WORKSPACE    = $WORKSPACE"
echo "  XorKey       = (auto-generated, 256 bits)"
echo "  Edit the file to set SMTP creds, captcha, etc. (or do it from /admin/settings after boot)"
echo "  It's chmod 600 + in .gitignore — never commit it."

if [ -n "$ADMIN_PASSWORD_GENERATED" ]; then
    echo ""
    echo "  ⚠ Auto-generated admin seed password (write this down — only shown once):"
    echo "      $ADMIN_PASSWORD"
    echo "  After 'make platform-up', log in as user 'Admin' with that password."
fi
